import type { Metadata } from "next";
import "./globals.css";
import { avant, clonoid } from "@/lib/fonts";
import { Inter } from "next/font/google";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";

export const metadata: Metadata = {
  title: "SUBER",
  description: "Generated by SUBER",
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${clonoid.variable} ${avant.variable}`}>
      <body
        className={`${inter.className} antialiased bg-[#020002] md:w-[450px] mx-auto h-dvh md:h-screen`}
        
      >
        {/* <main style={{backgroundImage: `url(${layoutBg.src})`}} className="h-full bg-contain bg-no-repeat bg-center"> */}
          <Header/>
            {children}
          <Footer/>
        {/* </main> */}
      </body>
    </html>
  );
}
