import type { Metadata } from "next";
import "./globals.css";
import { clonoid } from "@/lib/fonts";

export const metadata: Metadata = {
  title: "SUBER",
  description: "Generated by SUBER",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${clonoid.variable}`}>
      <body
        className={`antialiased bg-[#020002] w-full h-full`}
      >
        {children}
      </body>
    </html>
  );
}
